// Code generated by "stringer -type=Group"; DO NOT EDIT.

package restaurant

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Fasanenhof-1]
	_ = x[Esslingen-2]
	_ = x[Feuerbach-3]
}

const _Group_name = "FasanenhofEsslingenFeuerbach"

var _Group_index = [...]uint8{0, 10, 19, 28}

func (i Group) String() string {
	i -= 1
	if i >= Group(len(_Group_index)-1) {
		return "Group(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Group_name[_Group_index[i]:_Group_index[i+1]]
}
