services:
  dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
      args:
        FEDORA_VERSION: "38"
    hostname: dev
    command: air --build.exclude_dir "static,docs,storage,tmp,dist,logs"
    environment:
      - LOG_LEVEL=debug
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - 8080:8080
    volumes:
      - ./src:/src
