services:
  dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
      args:
        - GOLANG_VERSION=${GOLANG_VERSION}
    hostname: dev
    command: air -c .air.toml
    environment:
      - TZ=Europe/Berlin
      - LOG_LEVEL=debug
    ports:
      - 8080:8080
    volumes:
      - ./:/app/
