ARG V_GOLANG
FROM golang:${V_GOLANG}
RUN apt-get update -qq
RUN apt-get install -y imagemagick poppler-utils wv unrtf tidy
RUN sed -i '/disable ghostscript format types/,+6d' /etc/ImageMagick-6/policy.xml
RUN apt-get install -y libtesseract-dev libleptonica-dev
RUN apt-get install -y tesseract-ocr-eng tesseract-ocr-deu

RUN go install github.com/air-verse/air@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest
COPY ./.air.toml .

WORKDIR /app
COPY ./go.mod .
COPY ./go.sum .
RUN go mod download
