ARG FEDORA_VERSION
FROM fedora:${FEDORA_VERSION}
ENV GOPROXY=https://proxy.golang.org

RUN dnf -y upgrade --refresh
RUN dnf -y install golang
RUN dnf -y install tesseract tesseract-osd tesseract-langpack-deu tesseract-langpack-eng
RUN dnf -y install ImageMagick poppler-utils libwebp

# Mittag
WORKDIR /app
COPY ./go.mod .
COPY ./go.sum .
RUN go mod download

# Air
RUN go install github.com/cosmtrek/air@latest
COPY ./.air.toml .

# Envs
ENV VERSION=v0.0.0-DEV
ENV BUILDTIME=2023-06-01T08:07:43.454Z
ENV PATH "$PATH:/root/go/bin"
