ARG GOLANG_VERSION
FROM golang:${GOLANG_VERSION}
RUN apt-get update -qq
RUN apt-get install -y imagemagick poppler-utils wv unrtf tidy
RUN sed -i '/disable ghostscript format types/,+6d' /etc/ImageMagick-6/policy.xml
RUN apt-get install -y libtesseract-dev libleptonica-dev
RUN apt-get install -y tesseract-ocr-eng tesseract-ocr-deu

RUN go install github.com/cosmtrek/air@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest

WORKDIR /app
COPY ./go.mod .
COPY ./go.sum .
RUN go mod download

ENV APP_VERSION=v0.0.0-DEV
ENV BUILD_TIME=2023-06-01T08:07:43.454Z
