variables:
  GITHUB_REGISTRY: 'ghcr.io/$GITHUB_USER/mittag'
  DOCKER_VERSION: '24.0.2'
  GOLANG_VERSION: '1.20'
  NODE_VERSION: '18'
  ALPINE_VERSION: '3'
  DEBIAN_VERSION: '12'
  TELEPORT_VERSION: '13.1.1'
  PRODUCTION_URL: 'https://mittag.unjx.de'

image: docker:$DOCKER_VERSION-git

.login_registry:
  before_script:
    - echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USER --password-stdin

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
    - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
  cache:
    paths:
      - .go/pkg/mod/
