time_zone: "Europe/Berlin"
log_level: "info"
api_token: "replace-me"

server:
  address: "0.0.0.0"
  port: 8156

restaurants:
  avada:
    name: "Avada"
    tags: ["Asiatisch", "Sushi", "Japanisch", "Fisch", "Reis"]
    url: "https://avada-nt.de/mittagsmenu/"
    address: "Neckarstraße 1, 72622 Nürtingen"
    phone: "+49 7022 9796098"
    rest_days:
      - "Friday"
      - "Saturday"
    group: "Nürtingen"
    parse:
      update_cron: "30 9,10 * * 1,2"
      navigate:
        - locator: ".vamtam-grid:has(img)"
          style: "#qlwapp { display: none !important; }"

  benz:
    name: "Benz Metzgerei"
    tags: ["Metzgerei", "Fleisch", "Schnitzel", "Wurst", "Regional"]
    url: "https://benz-metzgerei-feinkost.de/schwanen-metzgerei/tagesessen/"
    address: "Hirschstraße 18, 73257 Köngen"
    phone: "+49 7024 81488"
    rest_days:
      - "Sunday"
    group: "Köngen"
    parse:
      update_cron: "30 9,10 * * 1,2"
      navigate:
        - locator: "#CookieBoxSaveButton"
        - locator: "//p[strong[contains(text(), '{{date(format=02.01.2006,day=friday,offset=-1)}}')]]/following-sibling::p[1]/a"
          attribute: "href"
      file_type: "image"

  blessing:
    name: "Blessing-Kurz"
    tags: ["Metzgerei", "Fleisch", "Wurst", "Hausgemacht", "Schwäbisch"]
    url: "https://blessing-kurz.de/de/tagesessen/"
    address: "Unterdorfstraße 1, 73257 Köngen"
    phone: "+49 7024 989895"
    rest_days:
      - "Sunday"
    group: "Köngen"
    parse:
      update_cron: "30 9,10 * * 1,2"
      navigate:
        - locator: "#cookieInfoBtnPrimary"
        - locator: "#tagesessen"

  damama:
    name: "Da Mama"
    tags: ["Italienisch", "Pizza", "Pasta", "Authentisch", "Antipasti"]
    url: "https://da-mamma.de/"
    address: "Bahnhofstraße 17, 73240 Wendlingen am Neckar"
    phone: "+49 7024 8685216"
    rest_days:
      - "Monday"
    group: "Wendlingen am Neckar"
    parse:
      update_cron: "30 9,10 * * 2,3"
      navigate:
        - locator: "#peehzr"

  davvero:
    name: "Davvero"
    tags: ["Italienisch", "Pizza", "Pasta", "Risotto", "Mediterran"]
    url: "https://www.davvero-stuttgart.de/index.html"
    address: "Lohäckerstraße 11, 70567 Stuttgart-Möhringen"
    phone: "+49 711 78784911"
    rest_days:
      - "Tuesday"
    group: "Möhringen"
    parse:
      update_cron: "30 9,10 * * 1,3"
      direct_download: "https://davvero-stuttgart.de/download/mittagskarte.pdf"
      file_type: "pdf"

  etcan:
    name: "Et.Can."
    tags: ["Steakhouse", "Fleisch", "Grill", "Steak", "Amerikanisch"]
    url: "https://et-can.de/mittagskarte/"
    address: "Schäferhauser Straße 18, 73240 Wendlingen am Neckar"
    phone: "+49 177 6474213"
    rest_days:
      - "Monday"
      - "Tuesday"
    group: "Wendlingen am Neckar"
    parse:
      update_cron: "30 9,10 * * 3,4"
      navigate:
        - locator: ".et_pb_section.et_pb_section_1.et_pb_with_background.et_section_regular"
          style: "#BorlabsCookieBox, #BorlabsCookieBoxWidget, #main-header { display: none !important; }"

  peppone:
    name: "Da Peppone"
    tags: ["Italienisch", "Pizza", "Pasta", "Ristorante", "Steinofen"]
    url: "https://dapeppone-restaurant.de/"
    address: "Ristorante u. Pizzeria Da Peppone, Bopseräcker 1, 70597 Stuttgart-Degerloch"
    phone: "+49 711 78784911"
    rest_days:
      - "Monday"
    group: "Degerloch"
    parse:
      update_cron: "30 9,10 * * 2,3"
      navigate:
        - locator: "//a[contains(text(), 'MITTAGSKARTE')]"
      file_type: "pdf"

  delta:
    name: "Delta"
    tags: ["Thailändisch", "Asiatisch", "Curry", "Scharf", "Reis"]
    url: "https://www.delta-koengen.de/menü/"
    address: "Plochinger Straße 22, 73257 Köngen"
    phone: "+49 7024 466833"
    rest_days:
      - "Monday"
    group: "Köngen"
    parse:
      update_cron: "30 9,10 * * 2,3"
      navigate:
        - locator: "#cookie-settings-reject-all"
        - locator: "//a[contains(text(), 'Download')]"
      file_type: "pdf"

  enbw:
    name: "EnBW"
    tags: ["Kantine", "Büffet", "Deutsch", "Mitarbeiter", "Günstig"]
    url: "https://www.enbw.com/unternehmen/standorte/stuttgart-fasanenhof/"
    address: "EnBW Kantine, Schelmenwasenstraße 15, 70567 Stuttgart-Fasanenhof"
    phone: "+49 721 72586001"
    rest_days:
      - "Sunday"
      - "Saturday"
    group: "Fasanenhof"

  fass:
    name: "Fass"
    tags: ["Deutsch", "Gasthaus", "Schwäbisch", "Schnitzel", "Hausmannskost"]
    url: "http://www.gasthaus-fass.de/mittagstisch"
    address: "Bahnhofstraße 10, 72644 Oberboihingen"
    phone: "+49 7022 61185"
    rest_days:
      - "Tuesday"
    group: "Nürtingen"
    parse:
      update_cron: "30 9,10 * * 1,3"
      navigate:
        - locator: "#maincontainer"
          style: ".sqrnav { display: none !important; }"

  linde:
    name: "Gasthaus Linde"
    tags: ["Metzgerei", "Fleisch", "Gasthaus", "Regional", "Schwäbisch"]
    url: "https://www.gasthauslinde.de/Mittagstisch"
    address: "Wasserburgstraße 3, 72622 Nürtingen-Zizishausen"
    phone: "+49 7022 62306"
    rest_days:
      - "Monday"
    group: "Nürtingen"
    parse:
      update_cron: "30 9,10 1-3 * *"
      navigate:
        - locator: "//a[contains(text(), 'Mittagstisch') and contains(text(), '{{date(format=Jan,lang=de,upper=true)}}')]"
      file_type: "pdf"

  munz:
    name: "Hoflieferant Munz"
    tags: ["Metzgerei", "Fleisch", "Wurst", "Premium", "Hoflieferant"]
    url: "https://www.hoflieferant-munz.de/aktuelles"
    address: "Stuttgarter Straße 23, 70469 Stuttgart-Feuerbach"
    phone: "+49 711 36591400"
    rest_days:
      - "Sunday"
    group: "Feuerbach"
    parse:
      update_cron: "30 9,10 * * 1,2"
      navigate:
        - locator: "//a[contains(text(), 'Download pdf')]"
      file_type: "pdf"

  khoi:
    name: "Khoi"
    tags: ["Vietnamesisch", "Asiatisch", "Pho", "Frisch", "Suppen"]
    url: "https://www.khoi-restaurant.de/speisekarte/"
    address: "Europaplatz 12, 70565 Stuttgart-Fasanenhof"
    phone: "+49 711 56619918"
    rest_days:
      - "Monday"
    group: "Fasanenhof"
    parse:
      update_cron: "30 9,10 * * 2,3"
      navigate:
        - locator: "//a[contains(text(), 'Mittagskarte PDF')]"
      file_type: "pdf"

  koe5:
    name: "KÖ5"
    tags: ["Deutsch", "Modern", "Bistro", "Burger", "Salate"]
    url: "https://koe5.de/"
    address: "Schelmenwasenstraße 5, 70567 Stuttgart-Fasanenhof"
    phone: "+49 711 99772624"
    rest_days:
      - "Saturday"
    group: "Fasanenhof"
    parse:
      update_cron: "30 9,10 * * 1,2"
      navigate:
        - locator: "//a[contains(text(), 'Alles ablehnen')]"
        - locator: "//div[@class='elementor-widget-container']"
          style: "#masthead { display: none !important; }"

  lunica:
    name: "L'unica"
    tags: ["Italienisch", "Pizza", "Pasta", "Fisch", "Elegant"]
    url: "https://www.lunica-restaurant.de/mittagstisch-lunica-restaurant-echterdingen.html"
    address: "Hauptstraße 33,70771 Leinfelden-Echterdingen"
    phone: "+49 711 78784708"
    rest_days:
      - "Sunday"
    group: "Leinfelden-Echterdingen"
    parse:
      update_cron: "30 9,10 * * 1,2"
      navigate:
        - locator: "[data-testid='uc-deny-all-button']"
        - locator: "div.row.mittagstisch_tafel"

  meet:
    name: "Meet & Eat"
    tags: ["Imbiss", "Schnell", "Burger", "Döner", "Günstig"]
    url: "http://meetundeat.com/"
    address: "Schelmenwasenstraße 7, 70567 Stuttgart-Fasanenhof"
    phone: "+49 157 30664255"
    rest_days:
      - "Sunday"
      - "Saturday"
    group: "Fasanenhof"
    parse:
      update_cron: "30 9,10 * * 1,2"
      navigate:
        - locator: "#speisekarte img"
          attribute: "src"
      file_type: "image"

  ochsen:
    name: "Ochsen"
    tags: ["Deutsch", "Gasthaus", "Schwäbisch", "Fleisch", "Tradionell"]
    url: "http://www.ochsen-koengen.de"
    address: "Oberdorfstraße 20, 73257 Köngen"
    phone: "+49 7024 81979"
    rest_days:
      - "Tuesday"
      - "Wednesday"
    group: "Köngen"
    parse:
      update_cron: "30 9,10 * * 1,4"
      navigate:
        - locator: "p.paragraph-mittagstisch-right-corona"
          style: ".w-nav { display: none !important; }"

  paulaner:
    name: "Paulaner"
    tags: ["Deutsch", "Bayerisch", "Bier", "Schnitzel", "Weißwurst"]
    url: "https://paulaner-le.de/speisen-getraenke/mittagstisch.html"
    address: "Burgstraße 4, 70771 Leinfelden-Echterdingen"
    phone: "+49 711 7944180"
    rest_days:
      - "Monday"
    group: "Leinfelden-Echterdingen"
    parse:
      update_cron: "30 9,10 * * 2,3"
      navigate:
        - locator: "//a[span[contains(text(), 'Zum Mittagsangebot')]]"
      file_type: "pdf"

  picchio:
    name: "Picchiorosso"
    tags: ["Italienisch", "Pizza", "Pasta", "Fisch", "Ristorante"]
    url: "https://picchiorosso.de/tageskarte/"
    address: "Ristorante Picchio Rosso, Zettachring 12, 70567 Stuttgart-Fasanenhof"
    phone: "+49 711 7156767"
    rest_days:
      - "Sunday"
      - "Saturday"
    group: "Fasanenhof"
    parse:
      update_cron: "30 9,10 * * 1-5"
      navigate:
        - locator: ".avia-cookie-consent-button"
        - locator: "//h2[contains(text(), 'Mittagskarte')]/ancestor::div[contains(@class, 'post-entry')]"
          style: "#header { display: none !important; } .av_textblock_section { display: none !important; } .hr { display: none !important; } .avia-button-wrap { display: none !important; }"

  stuben:
    name: "Ratsstuben"
    tags: ["Deutsch", "Gasthaus", "Regional", "Schnitzel", "Hausmannskost"]
    url: "https://ratsstuben.de/wochenkarte/"
    address: "Bernhäuser Straße 16, 70771 Leinfelden-Echterdingen"
    phone: "+49 711 791725"
    group: "Leinfelden-Echterdingen"
    parse:
      update_cron: "30 9,10 * * 1,2"
      navigate:
        - locator: "div > p > a"
      file_type: "pdf"

  schaible:
    name: "Schaible"
    tags: ["Metzgerei", "Fleisch", "Wurst", "Regional", "Handwerk"]
    url: "https://www.feuerbach.de/aktuelles/mittagstisch/"
    address: "Staufeneckstraße 1, 70469 Stuttgart-Feuerbach"
    phone: "+49 711 8104528"
    rest_days:
      - "Sunday"
      - "Monday"
    group: "Feuerbach"
    parse:
      update_cron: "30 9,10 * * 2,3"
      navigate:
        - locator: "//a[contains(text(), 'Schaible')]"
        - locator: ".cm-btn-success"
        - locator: "div.artikel.firmenportrait"
          style: ".fb-header { display: none !important; }"

  scheuer:
    name: "Schwedenscheuer"
    tags: ["Deutsch", "Schwedenplatte", "Fleisch", "Rustikal", "Gemütlich"]
    url: "https://www.schwedenscheuer.de/restaurant-leinfelden-echterdingen/tageskarte.html"
    address: "Hauptstraße 71/1, 70771 Leinfelden-Echterdingen"
    phone: "+49 711 7978527"
    rest_days:
      - "Sunday"
    group: "Leinfelden-Echterdingen"
    parse:
      update_cron: "30 9,10 * * 1,2"
      navigate:
        - locator: "[data-testid='uc-deny-all-button']"
        - locator: "#content"

  sw34:
    name: "SW34"
    tags: ["Eventlocation", "Modern", "Gehobene Küche", "Crossover", "Stylisch"]
    url: "https://sw34.restaurant/essen-trinken"
    address: "Schelmenwasenstraße 34, 70567 Stuttgart-Fasanenhof"
    phone: "+49 711 62042252"
    rest_days:
      - "Sunday"
      - "Saturday"
    group: "Fasanenhof"
    parse:
      update_cron: "30 9,10 * * 1,2"
      navigate:
        - locator: ".brlbs-btn-accept-only-essential"
        - locator: "#speisekarte"
          style: ".elementor-top-section.elementor-sticky.elementor-sticky--active, .brlbs-cmpnt-widget { display: none !important; }"

  troelsch:
    name: "Troelsch"
    tags: ["Bäckerei", "Backwaren", "Snacks", "Suppen", "Frühstück"]
    url: "https://www.troelsch.de/ueber-uns/standorte/"
    address: "Stuttgarter Straße 104, 70469 Stuttgart-Feuerbach"
    phone: "+49 711 85680030"
    group: "Feuerbach"
    parse:
      update_cron: "30 9,10 * * 1,2"
      navigate:
        - locator: "//h2[contains(text(), 'Feuerbach')]/parent::div/following-sibling::div//a[@title='Mittagskarte herunterladen']"
          attribute: "href"
          style: ".collapse:not(.show) { display: block !important; }"
      file_type: "pdf"
