// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetRestaurantData, GetRestaurantErrors, GetRestaurantResponses, GetRestaurantsData, GetRestaurantsErrors, GetRestaurantsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get restaurants with their current menu and details.
 *
 * Get restaurants with their current menu and details.
 */
export const getRestaurants = <ThrowOnError extends boolean = false>(options?: Options<GetRestaurantsData, ThrowOnError>) => (options?.client ?? client).get<GetRestaurantsResponses, GetRestaurantsErrors, ThrowOnError>({ url: '/api/restaurants', ...options });

/**
 * Get a restaurant by ID.
 *
 * Get a restaurant by ID.
 */
export const getRestaurant = <ThrowOnError extends boolean = false>(options: Options<GetRestaurantData, ThrowOnError>) => (options.client ?? client).get<GetRestaurantResponses, GetRestaurantErrors, ThrowOnError>({ url: '/api/restaurants/{id}', ...options });
