// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type Menu = {
    Height: string;
    Landscape: boolean;
    Modified: string | null;
    URL: string;
    Width: string;
};

export type Restaurant = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    address: string;
    created_at: string;
    group: string;
    id: string;
    menu: Menu;
    name: string;
    phone: string;
    rest_days: Array<string> | null;
    tags: Array<string> | null;
    url: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type RestaurantWritable = {
    address: string;
    created_at: string;
    group: string;
    id: string;
    menu: Menu;
    name: string;
    phone: string;
    rest_days: Array<string> | null;
    tags: Array<string> | null;
    url: string;
};

export type GetRestaurantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/restaurants';
};

export type GetRestaurantsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetRestaurantsError = GetRestaurantsErrors[keyof GetRestaurantsErrors];

export type GetRestaurantsResponses = {
    /**
     * OK
     */
    200: Array<Restaurant> | null;
};

export type GetRestaurantsResponse = GetRestaurantsResponses[keyof GetRestaurantsResponses];

export type GetRestaurantData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/restaurants/{id}';
};

export type GetRestaurantErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetRestaurantError = GetRestaurantErrors[keyof GetRestaurantErrors];

export type GetRestaurantResponses = {
    /**
     * OK
     */
    200: Restaurant;
};

export type GetRestaurantResponse = GetRestaurantResponses[keyof GetRestaurantResponses];
