basePath: /api/v1
definitions:
  echo.HTTPError:
    properties:
      message: {}
    required:
    - message
    type: object
  services.CleanRestaurant:
    properties:
      address:
        type: string
      description:
        type: string
      group:
        $ref: '#/definitions/services.Group'
      icon:
        type: string
      id:
        type: string
      image_url:
        type: string
      name:
        type: string
      page_url:
        type: string
      phone:
        type: string
      price:
        type: integer
      rest_days:
        items:
          $ref: '#/definitions/services.DayOfWeek'
        type: array
    required:
    - address
    - description
    - group
    - icon
    - id
    - image_url
    - name
    - page_url
    - phone
    - price
    - rest_days
    type: object
  services.DayOfWeek:
    enum:
    - Sunday
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    - Saturday
    type: string
    x-enum-varnames:
    - Sunday
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    - Saturday
  services.Group:
    enum:
    - Degerloch
    - Fasanenhof
    - Feuerbach
    - Köngen
    - Leinfelden-Echterdingen
    - Nürtingen
    type: string
    x-enum-varnames:
    - Degerloch
    - Fasanenhof
    - Feuerbach
    - Koengen
    - LeinfeldenEchterdingen
    - Nuertingen
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Mittagstisch API
  version: "1.0"
paths:
  /restaurants:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            additionalProperties:
              $ref: '#/definitions/services.CleanRestaurant'
            type: object
      summary: Get all restaurants
      tags:
      - restaurants
  /restaurants/{id}:
    get:
      parameters:
      - description: Restaurant ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/services.CleanRestaurant'
        "404":
          description: Can not find ID
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Get a single restaurant
      tags:
      - restaurants
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Bearer <Add access token here>
        in: header
        name: Authorization
        required: true
        type: string
      - description: Restaurant ID
        in: path
        name: id
        required: true
        type: string
      - description: Menu File
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/services.CleanRestaurant'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/echo.HTTPError'
        "404":
          description: Can not find ID
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: Upload a menu
      tags:
      - restaurants
swagger: "2.0"
