name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.ref_name }}
          labels: |
            maintainer=${{ github.actor }}
            org.opencontainers.image.title=Mittagskarte
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.description=Schniddzl.de - deine Mittagskarte
            org.opencontainers.image.vendor=flohoss
            org.opencontainers.image.version=${{ github.ref_name }}

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          file: docker/release.dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            V_GOLANG=${{ vars.V_GOLANG }}
            V_NODE=${{ vars.V_NODE }}
            V_ALPINE=${{ vars.V_ALPINE }}
            APP_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            BUILD_TIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            REPO=https://github.com/${{ github.repository }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
